version: "3"
services:
  web:
    image: nginx
    volumes:
     - ./proxy.conf.template:/etc/nginx/conf.d/proxy.conf.template
     - ./proxy.pac:/usr/share/nginx/html/proxy.pac
    ports:
     - "8082:80"
    environment:
     - NGINX_HOST=foobar.com
     - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/proxy.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
